"""Add source history and health status

Revision ID: 05c265ee3b3a
Revises: d9634a538d9c
Create Date: 2026-08-23 16:12:35.231395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05c265ee3b3a'
down_revision = 'd9634a538d9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('src_source_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['src_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('src_endpoint', sa.Column('consecutive_failures', sa.Integer(), nullable=True))
    op.add_column('src_endpoint', sa.Column('rate_limit_rpm', sa.Integer(), nullable=True))
    op.add_column('src_quarantine', sa.Column('action_taken', sa.String(length=100), nullable=True))
    op.add_column('src_quarantine', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('src_source', sa.Column('health_status', sa.String(length=50), nullable=False, server_default='UNKNOWN'))
    op.add_column('src_source', sa.Column('parent_source_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'src_source', 'src_source', ['parent_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'src_source', type_='foreignkey')
    op.drop_column('src_source', 'parent_source_id')
    op.drop_column('src_source', 'health_status')
    op.drop_column('src_quarantine', 'resolved_at')
    op.drop_column('src_quarantine', 'action_taken')
    op.drop_column('src_endpoint', 'rate_limit_rpm')
    op.drop_column('src_endpoint', 'consecutive_failures')
    op.drop_table('src_source_history')
    # ### end Alembic commands ###
