"""add_next_scheduled_at_to_endpoint

Revision ID: 5536d43abd83
Revises: f1c2c1d84e03
Create Date: 2026-08-22 14:13:38.951848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5536d43abd83'
down_revision = 'f1c2c1d84e03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('src_endpoint', sa.Column('next_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('src_endpoint', 'next_scheduled_at')
    # ### end Alembic commands ###
