"""Add source endpoint unique constraint

Revision ID: 80be1fdb0739
Revises: 05c265ee3b3a
Create Date: 2026-08-23 16:14:33.549264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80be1fdb0739'
down_revision = '05c265ee3b3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_src_endpoint_canonical_url', 'src_endpoint', ['source_id', 'canonical_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_src_endpoint_canonical_url', 'src_endpoint', type_='unique')
    # ### end Alembic commands ###
