"""advanced_versioning_v2

Revision ID: 89ab2f750dee
Revises: 0001_create_all_tables
Create Date: 2026-08-22 12:32:36.512270

"""
from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89ab2f750dee'
down_revision = '0001_create_all_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prov_canonical_fact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.String(length=256), nullable=False),
    sa.Column('attribute_name', sa.String(length=256), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('conflict_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('src_chunk_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('chunker_version', sa.String(length=50), nullable=False),
    sa.Column('chunking_policy_version', sa.String(length=50), nullable=True),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('heading', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['src_content_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('src_extracted_text_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['src_content_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('src_ocr_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('ocr_engine', sa.String(length=100), nullable=False),
    sa.Column('ocr_engine_version', sa.String(length=50), nullable=False),
    sa.Column('ocr_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['src_content_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('src_embedding_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_version_id', sa.UUID(), nullable=True),
    sa.Column('content_version_id', sa.UUID(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=50), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('embedding_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_version_id'], ['src_chunk_version.id'], ),
    sa.ForeignKeyConstraint(['content_version_id'], ['src_content_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ai_chunk', sa.Column('content_version_id', sa.UUID(), nullable=False))
    op.alter_column('ai_chunk', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'ai_chunk', 'src_content_version', ['content_version_id'], ['id'])
    op.add_column('ai_embedding', sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(), nullable=True))
    op.add_column('ai_embedding_model', sa.Column('version', sa.String(length=50), nullable=False))
    op.alter_column('ai_embedding_model', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('elec_candidate', sa.Column('raw_name', sa.String(length=255), nullable=False))
    op.alter_column('elec_candidate', 'person_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('elec_candidate_election_event_id_fkey', 'elec_candidate', type_='foreignkey')
    op.drop_column('elec_candidate', 'election_event_id')
    op.drop_column('elec_candidate', 'status')
    op.add_column('elec_election', sa.Column('type', sa.String(length=50), nullable=False))
    op.drop_column('elec_election', 'name')
    op.drop_column('elec_election', 'election_type')
    op.add_column('elec_event', sa.Column('phase', sa.Integer(), nullable=True))
    op.add_column('elec_event', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('elec_event_constituency_id_fkey', 'elec_event', type_='foreignkey')
    op.drop_column('elec_event', 'constituency_id')
    op.drop_column('elec_event', 'event_date')
    op.add_column('elec_result', sa.Column('event_id', sa.UUID(), nullable=False))
    op.add_column('elec_result', sa.Column('constituency_id', sa.UUID(), nullable=False))
    op.add_column('elec_result', sa.Column('vote_percentage', sa.Float(), nullable=True))
    op.add_column('elec_result', sa.Column('rank', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'elec_result', 'geo_entity', ['constituency_id'], ['id'])
    op.create_foreign_key(None, 'elec_result', 'elec_event', ['event_id'], ['id'])
    op.drop_column('elec_result', 'status')
    op.add_column('fin_allocation', sa.Column('project_id', sa.UUID(), nullable=False))
    op.add_column('fin_allocation', sa.Column('currency', sa.String(length=3), nullable=False))
    op.alter_column('fin_allocation', 'amount',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'fin_allocation', 'proj_project', ['project_id'], ['id'])
    op.add_column('fin_budget', sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('fin_budget', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('fin_budget', sa.Column('original_source_value', sa.String(length=255), nullable=False))
    op.drop_constraint('fin_budget_jurisdiction_id_fkey', 'fin_budget', type_='foreignkey')
    op.drop_column('fin_budget', 'total_allocation')
    op.drop_column('fin_budget', 'jurisdiction_id')
    op.add_column('fin_expenditure', sa.Column('work_id', sa.UUID(), nullable=False))
    op.add_column('fin_expenditure', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('fin_expenditure', 'amount',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.drop_constraint('fin_expenditure_release_id_fkey', 'fin_expenditure', type_='foreignkey')
    op.create_foreign_key(None, 'fin_expenditure', 'proj_work', ['work_id'], ['id'])
    op.drop_column('fin_expenditure', 'recorded_at')
    op.drop_column('fin_expenditure', 'release_id')
    op.add_column('fin_release', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('fin_release', 'amount',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.drop_column('fin_release', 'released_at')
    op.add_column('fin_year', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('fin_year', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'fin_year', ['label'])
    op.add_column('geo_entity', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('geo_entity', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('geo_entity', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('geo_entity', sa.Column('geom_simplified', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
# op.create_index('idx_geo_entity_geom', 'geo_entity', ['geom'], unique=False, postgresql_using='gist')
# op.create_index('idx_geo_entity_geom_simplified', 'geo_entity', ['geom_simplified'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_geo_entity_type'), 'geo_entity', ['type'], unique=False)
    op.drop_constraint('geo_entity_parent_id_fkey', 'geo_entity', type_='foreignkey')
    op.drop_column('geo_entity', 'canonical_name')
    op.drop_column('geo_entity', 'parent_id')
    op.drop_column('geo_entity', 'entity_type')
    op.add_column('geo_relationship', sa.Column('parent_id', sa.UUID(), nullable=False))
    op.add_column('geo_relationship', sa.Column('child_id', sa.UUID(), nullable=False))
    op.alter_column('geo_relationship', 'relationship_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_geo_relationship_relationship_type'), 'geo_relationship', ['relationship_type'], unique=False)
    op.drop_constraint('geo_relationship_to_entity_id_fkey', 'geo_relationship', type_='foreignkey')
    op.drop_constraint('geo_relationship_from_entity_id_fkey', 'geo_relationship', type_='foreignkey')
    op.create_foreign_key(None, 'geo_relationship', 'geo_entity', ['child_id'], ['id'])
    op.create_foreign_key(None, 'geo_relationship', 'geo_entity', ['parent_id'], ['id'])
    op.drop_column('geo_relationship', 'from_entity_id')
    op.drop_column('geo_relationship', 'to_entity_id')
    op.add_column('prov_claim', sa.Column('claim_level', sa.String(length=50), nullable=False))
    op.add_column('prov_claim', sa.Column('description', sa.String(length=1024), nullable=False))
    op.add_column('prov_claim', sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('prov_claim', sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prov_claim', sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prov_claim', sa.Column('canonical_fact_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'prov_claim', 'prov_canonical_fact', ['canonical_fact_id'], ['id'])
    op.drop_column('prov_claim', 'field_name')
    op.drop_column('prov_claim', 'entity_id')
    op.drop_column('prov_claim', 'entity_type')
    op.add_column('prov_evidence', sa.Column('endpoint_id', sa.UUID(), nullable=True))
    op.add_column('prov_evidence', sa.Column('document_id', sa.UUID(), nullable=True))
    op.add_column('prov_evidence', sa.Column('content_version_id', sa.UUID(), nullable=True))
    op.add_column('prov_evidence', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('prov_evidence', sa.Column('extracted_text_version_id', sa.UUID(), nullable=True))
    op.add_column('prov_evidence', sa.Column('record_id', sa.String(length=256), nullable=True))
    op.add_column('prov_evidence', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_foreign_key(None, 'prov_evidence', 'src_extracted_text_version', ['extracted_text_version_id'], ['id'])
    op.create_foreign_key(None, 'prov_evidence', 'src_content_version', ['content_version_id'], ['id'])
    op.create_foreign_key(None, 'prov_evidence', 'src_document', ['document_id'], ['id'])
    op.create_foreign_key(None, 'prov_evidence', 'src_endpoint', ['endpoint_id'], ['id'])
    op.drop_column('prov_evidence', 'confidence')
    op.drop_column('prov_evidence', 'value_text')
    op.add_column('src_content_version', sa.Column('sha256', sa.String(length=64), nullable=False))
    op.add_column('src_content_version', sa.Column('byte_size', sa.Integer(), nullable=True))
    op.add_column('src_content_version', sa.Column('mime_type', sa.String(length=256), nullable=True))
    op.add_column('src_content_version', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('src_content_version', sa.Column('storage_path', sa.String(length=1024), nullable=True))
    op.add_column('src_content_version', sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('src_document', sa.Column('source_id', sa.UUID(), nullable=True))
    op.add_column('src_document', sa.Column('document_type', sa.String(length=100), nullable=True))
    op.add_column('src_document', sa.Column('title', sa.String(length=1024), nullable=True))
    op.add_column('src_document', sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('src_document', sa.Column('canonical_url', sa.String(length=2048), nullable=True))
    op.add_column('src_document', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('src_document', sa.Column('relationship', sa.String(length=50), nullable=True))
    op.add_column('src_document', sa.Column('related_document_id', sa.UUID(), nullable=True))
    op.add_column('src_document', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('src_document_fetch_event_id_fkey', 'src_document', type_='foreignkey')
    op.create_foreign_key(None, 'src_document', 'src_document', ['related_document_id'], ['id'])
    op.create_foreign_key(None, 'src_document', 'src_source', ['source_id'], ['id'])
    op.drop_column('src_document', 'fetch_event_id')
    op.drop_column('src_document', 'raw_url')
    op.drop_column('src_document', 'content_hash')
    op.add_column('src_endpoint', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('src_endpoint', sa.Column('redirect_url', sa.String(length=2048), nullable=True))
    op.add_column('src_endpoint', sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('src_endpoint', sa.Column('endpoint_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('src_fetch_event', sa.Column('endpoint_id', sa.UUID(), nullable=True))
    op.add_column('src_fetch_event', sa.Column('content_length', sa.Integer(), nullable=True))
    op.add_column('src_fetch_event', sa.Column('etag', sa.String(length=256), nullable=True))
    op.add_column('src_fetch_event', sa.Column('last_modified', sa.String(length=256), nullable=True))
    op.add_column('src_fetch_event', sa.Column('redirect_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('src_fetch_event', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('src_fetch_event', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'src_fetch_event', 'src_endpoint', ['endpoint_id'], ['id'])
    op.add_column('src_source', sa.Column('authority_name', sa.String(length=512), nullable=True))
    op.add_column('src_source', sa.Column('authority_type', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('jurisdiction', sa.String(length=200), nullable=True))
    op.add_column('src_source', sa.Column('official_domain', sa.String(length=2048), nullable=True))
    op.add_column('src_source', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('src_source', sa.Column('license', sa.String(length=200), nullable=True))
    op.add_column('src_source', sa.Column('access_policy', sa.String(length=200), nullable=True))
    op.add_column('src_source', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('src_source', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('src_source', 'last_fetched')
    op.drop_column('src_source', 'official_url')
    op.add_column('sys_entity_resolution', sa.Column('raw_value', sa.String(length=1024), nullable=False))
    op.add_column('sys_entity_resolution', sa.Column('target_table', sa.String(length=100), nullable=False))
    op.add_column('sys_entity_resolution', sa.Column('candidate_id', sa.UUID(), nullable=True))
    op.add_column('sys_entity_resolution', sa.Column('matching_method', sa.String(length=100), nullable=False))
    op.add_column('sys_entity_resolution', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('sys_entity_resolution', sa.Column('reviewer', sa.String(length=255), nullable=True))
    op.add_column('sys_entity_resolution', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('sys_entity_resolution', 'source_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='source_id::uuid')
    op.create_foreign_key(None, 'sys_entity_resolution', 'src_source', ['source_id'], ['id'])
    op.drop_column('sys_entity_resolution', 'canonical_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_entity_resolution', sa.Column('canonical_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sys_entity_resolution', type_='foreignkey')
    op.alter_column('sys_entity_resolution', 'source_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.drop_column('sys_entity_resolution', 'resolved_at')
    op.drop_column('sys_entity_resolution', 'reviewer')
    op.drop_column('sys_entity_resolution', 'confidence')
    op.drop_column('sys_entity_resolution', 'matching_method')
    op.drop_column('sys_entity_resolution', 'candidate_id')
    op.drop_column('sys_entity_resolution', 'target_table')
    op.drop_column('sys_entity_resolution', 'raw_value')
    op.add_column('src_source', sa.Column('official_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.add_column('src_source', sa.Column('last_fetched', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('src_source', 'updated_at')
    op.drop_column('src_source', 'created_at')
    op.drop_column('src_source', 'access_policy')
    op.drop_column('src_source', 'license')
    op.drop_column('src_source', 'status')
    op.drop_column('src_source', 'official_domain')
    op.drop_column('src_source', 'jurisdiction')
    op.drop_column('src_source', 'authority_type')
    op.drop_column('src_source', 'authority_name')
    op.drop_constraint(None, 'src_fetch_event', type_='foreignkey')
    op.drop_column('src_fetch_event', 'content_hash')
    op.drop_column('src_fetch_event', 'error_message')
    op.drop_column('src_fetch_event', 'redirect_chain')
    op.drop_column('src_fetch_event', 'last_modified')
    op.drop_column('src_fetch_event', 'etag')
    op.drop_column('src_fetch_event', 'content_length')
    op.drop_column('src_fetch_event', 'endpoint_id')
    op.drop_column('src_endpoint', 'endpoint_schema')
    op.drop_column('src_endpoint', 'observed_at')
    op.drop_column('src_endpoint', 'redirect_url')
    op.drop_column('src_endpoint', 'status')
    op.add_column('src_document', sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('src_document', sa.Column('raw_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False))
    op.add_column('src_document', sa.Column('fetch_event_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'src_document', type_='foreignkey')
    op.drop_constraint(None, 'src_document', type_='foreignkey')
    op.create_foreign_key('src_document_fetch_event_id_fkey', 'src_document', 'src_fetch_event', ['fetch_event_id'], ['id'])
    op.drop_column('src_document', 'created_at')
    op.drop_column('src_document', 'related_document_id')
    op.drop_column('src_document', 'relationship')
    op.drop_column('src_document', 'status')
    op.drop_column('src_document', 'canonical_url')
    op.drop_column('src_document', 'publication_date')
    op.drop_column('src_document', 'title')
    op.drop_column('src_document', 'document_type')
    op.drop_column('src_document', 'source_id')
    op.drop_column('src_content_version', 'retrieved_at')
    op.drop_column('src_content_version', 'storage_path')
    op.drop_column('src_content_version', 'page_count')
    op.drop_column('src_content_version', 'mime_type')
    op.drop_column('src_content_version', 'byte_size')
    op.drop_column('src_content_version', 'sha256')
    op.add_column('prov_evidence', sa.Column('value_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('prov_evidence', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prov_evidence', type_='foreignkey')
    op.drop_constraint(None, 'prov_evidence', type_='foreignkey')
    op.drop_constraint(None, 'prov_evidence', type_='foreignkey')
    op.drop_constraint(None, 'prov_evidence', type_='foreignkey')
    op.drop_column('prov_evidence', 'created_at')
    op.drop_column('prov_evidence', 'record_id')
    op.drop_column('prov_evidence', 'extracted_text_version_id')
    op.drop_column('prov_evidence', 'page_number')
    op.drop_column('prov_evidence', 'content_version_id')
    op.drop_column('prov_evidence', 'document_id')
    op.drop_column('prov_evidence', 'endpoint_id')
    op.add_column('prov_claim', sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('prov_claim', sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('prov_claim', sa.Column('field_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prov_claim', type_='foreignkey')
    op.drop_column('prov_claim', 'canonical_fact_id')
    op.drop_column('prov_claim', 'valid_until')
    op.drop_column('prov_claim', 'valid_from')
    op.drop_column('prov_claim', 'observed_at')
    op.drop_column('prov_claim', 'description')
    op.drop_column('prov_claim', 'claim_level')
    op.add_column('geo_relationship', sa.Column('to_entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('geo_relationship', sa.Column('from_entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'geo_relationship', type_='foreignkey')
    op.drop_constraint(None, 'geo_relationship', type_='foreignkey')
    op.create_foreign_key('geo_relationship_from_entity_id_fkey', 'geo_relationship', 'geo_entity', ['from_entity_id'], ['id'])
    op.create_foreign_key('geo_relationship_to_entity_id_fkey', 'geo_relationship', 'geo_entity', ['to_entity_id'], ['id'])
    op.drop_index(op.f('ix_geo_relationship_relationship_type'), table_name='geo_relationship')
    op.alter_column('geo_relationship', 'relationship_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('geo_relationship', 'child_id')
    op.drop_column('geo_relationship', 'parent_id')
    op.add_column('geo_entity', sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('geo_entity', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('geo_entity', sa.Column('canonical_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_foreign_key('geo_entity_parent_id_fkey', 'geo_entity', 'geo_entity', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_geo_entity_type'), table_name='geo_entity')
    op.drop_index('idx_geo_entity_geom_simplified', table_name='geo_entity', postgresql_using='gist')
    op.drop_index('idx_geo_entity_geom', table_name='geo_entity', postgresql_using='gist')
    op.drop_column('geo_entity', 'geom_simplified')
    op.drop_column('geo_entity', 'geom')
    op.drop_column('geo_entity', 'name')
    op.drop_column('geo_entity', 'type')
    op.drop_constraint(None, 'fin_year', type_='unique')
    op.drop_column('fin_year', 'end_date')
    op.drop_column('fin_year', 'start_date')
    op.add_column('fin_release', sa.Column('released_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('fin_release', 'amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.drop_column('fin_release', 'date')
    op.add_column('fin_expenditure', sa.Column('release_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('fin_expenditure', sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fin_expenditure', type_='foreignkey')
    op.create_foreign_key('fin_expenditure_release_id_fkey', 'fin_expenditure', 'fin_release', ['release_id'], ['id'])
    op.alter_column('fin_expenditure', 'amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.drop_column('fin_expenditure', 'date')
    op.drop_column('fin_expenditure', 'work_id')
    op.add_column('fin_budget', sa.Column('jurisdiction_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('fin_budget', sa.Column('total_allocation', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True))
    op.create_foreign_key('fin_budget_jurisdiction_id_fkey', 'fin_budget', 'geo_entity', ['jurisdiction_id'], ['id'])
    op.drop_column('fin_budget', 'original_source_value')
    op.drop_column('fin_budget', 'currency')
    op.drop_column('fin_budget', 'amount')
    op.drop_constraint(None, 'fin_allocation', type_='foreignkey')
    op.alter_column('fin_allocation', 'amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.drop_column('fin_allocation', 'currency')
    op.drop_column('fin_allocation', 'project_id')
    op.add_column('elec_result', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'elec_result', type_='foreignkey')
    op.drop_constraint(None, 'elec_result', type_='foreignkey')
    op.drop_column('elec_result', 'rank')
    op.drop_column('elec_result', 'vote_percentage')
    op.drop_column('elec_result', 'constituency_id')
    op.drop_column('elec_result', 'event_id')
    op.add_column('elec_event', sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('elec_event', sa.Column('constituency_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('elec_event_constituency_id_fkey', 'elec_event', 'geo_entity', ['constituency_id'], ['id'])
    op.drop_column('elec_event', 'date')
    op.drop_column('elec_event', 'phase')
    op.add_column('elec_election', sa.Column('election_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('elec_election', sa.Column('name', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_column('elec_election', 'type')
    op.add_column('elec_candidate', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('elec_candidate', sa.Column('election_event_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('elec_candidate_election_event_id_fkey', 'elec_candidate', 'elec_event', ['election_event_id'], ['id'])
    op.alter_column('elec_candidate', 'person_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('elec_candidate', 'raw_name')
    op.alter_column('ai_embedding_model', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('ai_embedding_model', 'version')
    op.drop_column('ai_embedding', 'vector')
    op.drop_constraint(None, 'ai_chunk', type_='foreignkey')
    op.alter_column('ai_chunk', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('ai_chunk', 'content_version_id')
    op.drop_table('src_embedding_version')
    op.drop_table('src_ocr_version')
    op.drop_table('src_extracted_text_version')
    op.drop_table('src_chunk_version')
    op.drop_table('prov_canonical_fact')
    # ### end Alembic commands ###
