"""add_observation_model

Revision ID: c184b591c559
Revises: cd9dd48cdd60
Create Date: 2026-08-22 13:12:32.898592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c184b591c559'
down_revision = 'cd9dd48cdd60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('src_observation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('content_version_id', sa.UUID(), nullable=True),
    sa.Column('web_page_id', sa.UUID(), nullable=True),
    sa.Column('web_page_version_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_location', sa.String(length=512), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['content_version_id'], ['src_content_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['src_document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['src_source.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['web_page_id'], ['src_web_page.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['web_page_version_id'], ['src_web_page_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_src_observation_content_version_id'), 'src_observation', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_src_observation_document_id'), 'src_observation', ['document_id'], unique=False)
    op.create_index(op.f('ix_src_observation_source_id'), 'src_observation', ['source_id'], unique=False)
    op.create_index(op.f('ix_src_observation_web_page_id'), 'src_observation', ['web_page_id'], unique=False)
    op.create_index(op.f('ix_src_observation_web_page_version_id'), 'src_observation', ['web_page_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_src_observation_web_page_version_id'), table_name='src_observation')
    op.drop_index(op.f('ix_src_observation_web_page_id'), table_name='src_observation')
    op.drop_index(op.f('ix_src_observation_source_id'), table_name='src_observation')
    op.drop_index(op.f('ix_src_observation_document_id'), table_name='src_observation')
    op.drop_index(op.f('ix_src_observation_content_version_id'), table_name='src_observation')
    op.drop_table('src_observation')
    # ### end Alembic commands ###
