"""add_quarantine_table

Revision ID: c509fcc14e0a
Revises: 5536d43abd83
Create Date: 2026-08-22 22:00:58.150809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c509fcc14e0a'
down_revision = '5536d43abd83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('src_quarantine',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('endpoint_id', sa.UUID(), nullable=True),
    sa.Column('artifact_path', sa.String(length=1024), nullable=True),
    sa.Column('error_type', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['src_endpoint.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['src_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('src_quarantine')
    # ### end Alembic commands ###
