"""add_web_page_models

Revision ID: cd9dd48cdd60
Revises: 89ab2f750dee
Create Date: 2026-08-22 13:04:51.244876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9dd48cdd60'
down_revision = '89ab2f750dee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('src_web_page',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=True),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('current_url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('page_type', sa.Enum('HOME', 'INDEX', 'LISTING', 'DETAIL', 'ARTICLE', 'PRESS_RELEASE', 'NOTIFICATION', 'TENDER', 'BUDGET', 'DATASET', 'DASHBOARD', 'REPORT', 'POLICY', 'STATISTICS', 'CONTACT', 'ARCHIVE', 'UNKNOWN', name='pagetype'), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('parent_page_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['src_endpoint.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_page_id'], ['src_web_page.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['src_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'canonical_url', name='uq_web_page_canonical_url')
    )
    op.create_index(op.f('ix_src_web_page_canonical_url'), 'src_web_page', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_src_web_page_endpoint_id'), 'src_web_page', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_src_web_page_page_type'), 'src_web_page', ['page_type'], unique=False)
    op.create_index(op.f('ix_src_web_page_source_id'), 'src_web_page', ['source_id'], unique=False)
    op.create_table('src_web_page_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_html_hash', sa.String(length=64), nullable=False),
    sa.Column('change_type', sa.Enum('NO_CHANGE', 'METADATA_CHANGE', 'CONTENT_CHANGE', 'STRUCTURAL_CHANGE', 'UNKNOWN_CHANGE', name='changetype'), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('normalized_path', sa.String(length=1024), nullable=False),
    sa.Column('extracted_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['src_web_page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_src_web_page_version_content_hash'), 'src_web_page_version', ['content_hash'], unique=False)
    op.create_index(op.f('ix_src_web_page_version_page_id'), 'src_web_page_version', ['page_id'], unique=False)
    op.create_table('src_extracted_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('web_version_id', sa.UUID(), nullable=True),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=512), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['src_content_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['web_version_id'], ['src_web_page_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_src_extracted_table_document_version_id'), 'src_extracted_table', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_src_extracted_table_web_version_id'), 'src_extracted_table', ['web_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_src_extracted_table_web_version_id'), table_name='src_extracted_table')
    op.drop_index(op.f('ix_src_extracted_table_document_version_id'), table_name='src_extracted_table')
    op.drop_table('src_extracted_table')
    op.drop_index(op.f('ix_src_web_page_version_page_id'), table_name='src_web_page_version')
    op.drop_index(op.f('ix_src_web_page_version_content_hash'), table_name='src_web_page_version')
    op.drop_table('src_web_page_version')
    op.drop_index(op.f('ix_src_web_page_source_id'), table_name='src_web_page')
    op.drop_index(op.f('ix_src_web_page_page_type'), table_name='src_web_page')
    op.drop_index(op.f('ix_src_web_page_endpoint_id'), table_name='src_web_page')
    op.drop_index(op.f('ix_src_web_page_canonical_url'), table_name='src_web_page')
    op.drop_table('src_web_page')
    # ### end Alembic commands ###
