"""add_ingestion_batch

Revision ID: d9634a538d9c
Revises: c509fcc14e0a
Create Date: 2026-08-22 23:01:23.577142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9634a538d9c'
down_revision = 'c509fcc14e0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('src_ingestion_batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=True),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('src_ingestion_batch')
    # ### end Alembic commands ###
