"""advanced_versioning

Revision ID: ef59f855e06e
Revises: 0001_create_all_tables
Create Date: 2026-08-22 12:00:23.572881

"""
from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef59f855e06e'
down_revision = '0001_create_all_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prov_canonical_fact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.String(length=256), nullable=False),
    sa.Column('attribute_name', sa.String(length=256), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('conflict_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('src_chunk_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('chunker_version', sa.String(length=50), nullable=False),
    sa.Column('chunking_policy_version', sa.String(length=50), nullable=True),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('heading', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['src_content_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('src_extracted_text_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['src_content_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('src_ocr_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('ocr_engine', sa.String(length=100), nullable=False),
    sa.Column('ocr_engine_version', sa.String(length=50), nullable=False),
    sa.Column('ocr_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['src_content_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('src_embedding_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_version_id', sa.UUID(), nullable=True),
    sa.Column('content_version_id', sa.UUID(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=50), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('embedding_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_version_id'], ['src_chunk_version.id'], ),
    sa.ForeignKeyConstraint(['content_version_id'], ['src_content_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.add_column('ai_chunk', sa.Column('content_version_id', sa.UUID(), nullable=False))
    op.alter_column('ai_chunk', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'ai_chunk', 'src_content_version', ['content_version_id'], ['id'])
    op.add_column('ai_embedding', sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(), nullable=True))
    op.add_column('ai_embedding_model', sa.Column('version', sa.String(length=50), nullable=False))
    op.alter_column('ai_embedding_model', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('elec_candidate', sa.Column('raw_name', sa.String(length=255), nullable=False))
    op.alter_column('elec_candidate', 'person_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('elec_candidate_election_event_id_fkey', 'elec_candidate', type_='foreignkey')
    op.drop_column('elec_candidate', 'election_event_id')
    op.drop_column('elec_candidate', 'status')
    op.add_column('elec_election', sa.Column('type', sa.String(length=50), nullable=False))
    op.drop_column('elec_election', 'name')
    op.drop_column('elec_election', 'election_type')
    op.add_column('elec_event', sa.Column('phase', sa.Integer(), nullable=True))
    op.add_column('elec_event', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('elec_event_constituency_id_fkey', 'elec_event', type_='foreignkey')
    op.drop_column('elec_event', 'constituency_id')
    op.drop_column('elec_event', 'event_date')
    op.add_column('elec_result', sa.Column('event_id', sa.UUID(), nullable=False))
    op.add_column('elec_result', sa.Column('constituency_id', sa.UUID(), nullable=False))
    op.add_column('elec_result', sa.Column('vote_percentage', sa.Float(), nullable=True))
    op.add_column('elec_result', sa.Column('rank', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'elec_result', 'geo_entity', ['constituency_id'], ['id'])
    op.create_foreign_key(None, 'elec_result', 'elec_event', ['event_id'], ['id'])
    op.drop_column('elec_result', 'status')
    op.add_column('fin_allocation', sa.Column('project_id', sa.UUID(), nullable=False))
    op.add_column('fin_allocation', sa.Column('currency', sa.String(length=3), nullable=False))
    op.alter_column('fin_allocation', 'amount',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'fin_allocation', 'proj_project', ['project_id'], ['id'])
    op.add_column('fin_budget', sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('fin_budget', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('fin_budget', sa.Column('original_source_value', sa.String(length=255), nullable=False))
    op.drop_constraint('fin_budget_jurisdiction_id_fkey', 'fin_budget', type_='foreignkey')
    op.drop_column('fin_budget', 'jurisdiction_id')
    op.drop_column('fin_budget', 'total_allocation')
    op.add_column('fin_expenditure', sa.Column('work_id', sa.UUID(), nullable=False))
    op.add_column('fin_expenditure', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('fin_expenditure', 'amount',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.drop_constraint('fin_expenditure_release_id_fkey', 'fin_expenditure', type_='foreignkey')
    op.create_foreign_key(None, 'fin_expenditure', 'proj_work', ['work_id'], ['id'])
    op.drop_column('fin_expenditure', 'release_id')
    op.drop_column('fin_expenditure', 'recorded_at')
    op.add_column('fin_release', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('fin_release', 'amount',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.drop_column('fin_release', 'released_at')
    op.add_column('fin_year', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('fin_year', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'fin_year', ['label'])
    op.add_column('geo_entity', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('geo_entity', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('geo_entity', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('geo_entity', sa.Column('geom_simplified', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_geo_entity_geom', 'geo_entity', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_geo_entity_geom_simplified', 'geo_entity', ['geom_simplified'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_geo_entity_type'), 'geo_entity', ['type'], unique=False)
    op.drop_constraint('geo_entity_parent_id_fkey', 'geo_entity', type_='foreignkey')
    op.drop_column('geo_entity', 'parent_id')
    op.drop_column('geo_entity', 'canonical_name')
    op.drop_column('geo_entity', 'entity_type')
    op.add_column('geo_relationship', sa.Column('parent_id', sa.UUID(), nullable=False))
    op.add_column('geo_relationship', sa.Column('child_id', sa.UUID(), nullable=False))
    op.alter_column('geo_relationship', 'relationship_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_geo_relationship_relationship_type'), 'geo_relationship', ['relationship_type'], unique=False)
    op.drop_constraint('geo_relationship_to_entity_id_fkey', 'geo_relationship', type_='foreignkey')
    op.drop_constraint('geo_relationship_from_entity_id_fkey', 'geo_relationship', type_='foreignkey')
    op.create_foreign_key(None, 'geo_relationship', 'geo_entity', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'geo_relationship', 'geo_entity', ['child_id'], ['id'])
    op.drop_column('geo_relationship', 'from_entity_id')
    op.drop_column('geo_relationship', 'to_entity_id')
    op.add_column('prov_claim', sa.Column('claim_level', sa.String(length=50), nullable=False))
    op.add_column('prov_claim', sa.Column('description', sa.String(length=1024), nullable=False))
    op.add_column('prov_claim', sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('prov_claim', sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prov_claim', sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prov_claim', sa.Column('canonical_fact_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'prov_claim', 'prov_canonical_fact', ['canonical_fact_id'], ['id'])
    op.drop_column('prov_claim', 'entity_type')
    op.drop_column('prov_claim', 'field_name')
    op.drop_column('prov_claim', 'entity_id')
    op.add_column('prov_evidence', sa.Column('endpoint_id', sa.UUID(), nullable=True))
    op.add_column('prov_evidence', sa.Column('document_id', sa.UUID(), nullable=True))
    op.add_column('prov_evidence', sa.Column('content_version_id', sa.UUID(), nullable=True))
    op.add_column('prov_evidence', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('prov_evidence', sa.Column('extracted_text_version_id', sa.UUID(), nullable=True))
    op.add_column('prov_evidence', sa.Column('record_id', sa.String(length=256), nullable=True))
    op.add_column('prov_evidence', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_foreign_key(None, 'prov_evidence', 'src_extracted_text_version', ['extracted_text_version_id'], ['id'])
    op.create_foreign_key(None, 'prov_evidence', 'src_endpoint', ['endpoint_id'], ['id'])
    op.create_foreign_key(None, 'prov_evidence', 'src_document', ['document_id'], ['id'])
    op.create_foreign_key(None, 'prov_evidence', 'src_content_version', ['content_version_id'], ['id'])
    op.drop_column('prov_evidence', 'value_text')
    op.drop_column('prov_evidence', 'confidence')
    op.add_column('src_content_version', sa.Column('sha256', sa.String(length=64), nullable=False))
    op.add_column('src_content_version', sa.Column('byte_size', sa.Integer(), nullable=True))
    op.add_column('src_content_version', sa.Column('mime_type', sa.String(length=256), nullable=True))
    op.add_column('src_content_version', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('src_content_version', sa.Column('storage_path', sa.String(length=1024), nullable=True))
    op.add_column('src_content_version', sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('src_document', sa.Column('source_id', sa.UUID(), nullable=True))
    op.add_column('src_document', sa.Column('document_type', sa.String(length=100), nullable=True))
    op.add_column('src_document', sa.Column('title', sa.String(length=1024), nullable=True))
    op.add_column('src_document', sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('src_document', sa.Column('canonical_url', sa.String(length=2048), nullable=True))
    op.add_column('src_document', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('src_document', sa.Column('relationship', sa.String(length=50), nullable=True))
    op.add_column('src_document', sa.Column('related_document_id', sa.UUID(), nullable=True))
    op.add_column('src_document', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('src_document_fetch_event_id_fkey', 'src_document', type_='foreignkey')
    op.create_foreign_key(None, 'src_document', 'src_source', ['source_id'], ['id'])
    op.create_foreign_key(None, 'src_document', 'src_document', ['related_document_id'], ['id'])
    op.drop_column('src_document', 'fetch_event_id')
    op.drop_column('src_document', 'content_hash')
    op.drop_column('src_document', 'raw_url')
    op.add_column('src_endpoint', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('src_endpoint', sa.Column('redirect_url', sa.String(length=2048), nullable=True))
    op.add_column('src_endpoint', sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('src_endpoint', sa.Column('endpoint_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('src_fetch_event', sa.Column('endpoint_id', sa.UUID(), nullable=True))
    op.add_column('src_fetch_event', sa.Column('content_length', sa.Integer(), nullable=True))
    op.add_column('src_fetch_event', sa.Column('etag', sa.String(length=256), nullable=True))
    op.add_column('src_fetch_event', sa.Column('last_modified', sa.String(length=256), nullable=True))
    op.add_column('src_fetch_event', sa.Column('redirect_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('src_fetch_event', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('src_fetch_event', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'src_fetch_event', 'src_endpoint', ['endpoint_id'], ['id'])
    op.add_column('src_source', sa.Column('authority_name', sa.String(length=512), nullable=True))
    op.add_column('src_source', sa.Column('authority_type', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('jurisdiction', sa.String(length=200), nullable=True))
    op.add_column('src_source', sa.Column('official_domain', sa.String(length=2048), nullable=True))
    op.add_column('src_source', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('src_source', sa.Column('license', sa.String(length=200), nullable=True))
    op.add_column('src_source', sa.Column('access_policy', sa.String(length=200), nullable=True))
    op.add_column('src_source', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('src_source', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('src_source', 'official_url')
    op.drop_column('src_source', 'last_fetched')
    op.add_column('sys_entity_resolution', sa.Column('raw_value', sa.String(length=1024), nullable=False))
    op.add_column('sys_entity_resolution', sa.Column('target_table', sa.String(length=100), nullable=False))
    op.add_column('sys_entity_resolution', sa.Column('candidate_id', sa.UUID(), nullable=True))
    op.add_column('sys_entity_resolution', sa.Column('matching_method', sa.String(length=100), nullable=False))
    op.add_column('sys_entity_resolution', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('sys_entity_resolution', sa.Column('reviewer', sa.String(length=255), nullable=True))
    op.add_column('sys_entity_resolution', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('sys_entity_resolution', 'source_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(None, 'sys_entity_resolution', 'src_source', ['source_id'], ['id'])
    op.drop_column('sys_entity_resolution', 'canonical_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_entity_resolution', sa.Column('canonical_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sys_entity_resolution', type_='foreignkey')
    op.alter_column('sys_entity_resolution', 'source_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.drop_column('sys_entity_resolution', 'resolved_at')
    op.drop_column('sys_entity_resolution', 'reviewer')
    op.drop_column('sys_entity_resolution', 'confidence')
    op.drop_column('sys_entity_resolution', 'matching_method')
    op.drop_column('sys_entity_resolution', 'candidate_id')
    op.drop_column('sys_entity_resolution', 'target_table')
    op.drop_column('sys_entity_resolution', 'raw_value')
    op.add_column('src_source', sa.Column('last_fetched', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('src_source', sa.Column('official_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('src_source', 'updated_at')
    op.drop_column('src_source', 'created_at')
    op.drop_column('src_source', 'access_policy')
    op.drop_column('src_source', 'license')
    op.drop_column('src_source', 'status')
    op.drop_column('src_source', 'official_domain')
    op.drop_column('src_source', 'jurisdiction')
    op.drop_column('src_source', 'authority_type')
    op.drop_column('src_source', 'authority_name')
    op.drop_constraint(None, 'src_fetch_event', type_='foreignkey')
    op.drop_column('src_fetch_event', 'content_hash')
    op.drop_column('src_fetch_event', 'error_message')
    op.drop_column('src_fetch_event', 'redirect_chain')
    op.drop_column('src_fetch_event', 'last_modified')
    op.drop_column('src_fetch_event', 'etag')
    op.drop_column('src_fetch_event', 'content_length')
    op.drop_column('src_fetch_event', 'endpoint_id')
    op.drop_column('src_endpoint', 'endpoint_schema')
    op.drop_column('src_endpoint', 'observed_at')
    op.drop_column('src_endpoint', 'redirect_url')
    op.drop_column('src_endpoint', 'status')
    op.add_column('src_document', sa.Column('raw_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False))
    op.add_column('src_document', sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('src_document', sa.Column('fetch_event_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'src_document', type_='foreignkey')
    op.drop_constraint(None, 'src_document', type_='foreignkey')
    op.create_foreign_key('src_document_fetch_event_id_fkey', 'src_document', 'src_fetch_event', ['fetch_event_id'], ['id'])
    op.drop_column('src_document', 'created_at')
    op.drop_column('src_document', 'related_document_id')
    op.drop_column('src_document', 'relationship')
    op.drop_column('src_document', 'status')
    op.drop_column('src_document', 'canonical_url')
    op.drop_column('src_document', 'publication_date')
    op.drop_column('src_document', 'title')
    op.drop_column('src_document', 'document_type')
    op.drop_column('src_document', 'source_id')
    op.drop_column('src_content_version', 'retrieved_at')
    op.drop_column('src_content_version', 'storage_path')
    op.drop_column('src_content_version', 'page_count')
    op.drop_column('src_content_version', 'mime_type')
    op.drop_column('src_content_version', 'byte_size')
    op.drop_column('src_content_version', 'sha256')
    op.add_column('prov_evidence', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('prov_evidence', sa.Column('value_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prov_evidence', type_='foreignkey')
    op.drop_constraint(None, 'prov_evidence', type_='foreignkey')
    op.drop_constraint(None, 'prov_evidence', type_='foreignkey')
    op.drop_constraint(None, 'prov_evidence', type_='foreignkey')
    op.drop_column('prov_evidence', 'created_at')
    op.drop_column('prov_evidence', 'record_id')
    op.drop_column('prov_evidence', 'extracted_text_version_id')
    op.drop_column('prov_evidence', 'page_number')
    op.drop_column('prov_evidence', 'content_version_id')
    op.drop_column('prov_evidence', 'document_id')
    op.drop_column('prov_evidence', 'endpoint_id')
    op.add_column('prov_claim', sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('prov_claim', sa.Column('field_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('prov_claim', sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prov_claim', type_='foreignkey')
    op.drop_column('prov_claim', 'canonical_fact_id')
    op.drop_column('prov_claim', 'valid_until')
    op.drop_column('prov_claim', 'valid_from')
    op.drop_column('prov_claim', 'observed_at')
    op.drop_column('prov_claim', 'description')
    op.drop_column('prov_claim', 'claim_level')
    op.add_column('geo_relationship', sa.Column('to_entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('geo_relationship', sa.Column('from_entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'geo_relationship', type_='foreignkey')
    op.drop_constraint(None, 'geo_relationship', type_='foreignkey')
    op.create_foreign_key('geo_relationship_from_entity_id_fkey', 'geo_relationship', 'geo_entity', ['from_entity_id'], ['id'])
    op.create_foreign_key('geo_relationship_to_entity_id_fkey', 'geo_relationship', 'geo_entity', ['to_entity_id'], ['id'])
    op.drop_index(op.f('ix_geo_relationship_relationship_type'), table_name='geo_relationship')
    op.alter_column('geo_relationship', 'relationship_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('geo_relationship', 'child_id')
    op.drop_column('geo_relationship', 'parent_id')
    op.add_column('geo_entity', sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('geo_entity', sa.Column('canonical_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('geo_entity', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('geo_entity_parent_id_fkey', 'geo_entity', 'geo_entity', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_geo_entity_type'), table_name='geo_entity')
    op.drop_index('idx_geo_entity_geom_simplified', table_name='geo_entity', postgresql_using='gist')
    op.drop_index('idx_geo_entity_geom', table_name='geo_entity', postgresql_using='gist')
    op.drop_column('geo_entity', 'geom_simplified')
    op.drop_column('geo_entity', 'geom')
    op.drop_column('geo_entity', 'name')
    op.drop_column('geo_entity', 'type')
    op.drop_constraint(None, 'fin_year', type_='unique')
    op.drop_column('fin_year', 'end_date')
    op.drop_column('fin_year', 'start_date')
    op.add_column('fin_release', sa.Column('released_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('fin_release', 'amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.drop_column('fin_release', 'date')
    op.add_column('fin_expenditure', sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('fin_expenditure', sa.Column('release_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fin_expenditure', type_='foreignkey')
    op.create_foreign_key('fin_expenditure_release_id_fkey', 'fin_expenditure', 'fin_release', ['release_id'], ['id'])
    op.alter_column('fin_expenditure', 'amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.drop_column('fin_expenditure', 'date')
    op.drop_column('fin_expenditure', 'work_id')
    op.add_column('fin_budget', sa.Column('total_allocation', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True))
    op.add_column('fin_budget', sa.Column('jurisdiction_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('fin_budget_jurisdiction_id_fkey', 'fin_budget', 'geo_entity', ['jurisdiction_id'], ['id'])
    op.drop_column('fin_budget', 'original_source_value')
    op.drop_column('fin_budget', 'currency')
    op.drop_column('fin_budget', 'amount')
    op.drop_constraint(None, 'fin_allocation', type_='foreignkey')
    op.alter_column('fin_allocation', 'amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.drop_column('fin_allocation', 'currency')
    op.drop_column('fin_allocation', 'project_id')
    op.add_column('elec_result', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'elec_result', type_='foreignkey')
    op.drop_constraint(None, 'elec_result', type_='foreignkey')
    op.drop_column('elec_result', 'rank')
    op.drop_column('elec_result', 'vote_percentage')
    op.drop_column('elec_result', 'constituency_id')
    op.drop_column('elec_result', 'event_id')
    op.add_column('elec_event', sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('elec_event', sa.Column('constituency_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('elec_event_constituency_id_fkey', 'elec_event', 'geo_entity', ['constituency_id'], ['id'])
    op.drop_column('elec_event', 'date')
    op.drop_column('elec_event', 'phase')
    op.add_column('elec_election', sa.Column('election_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('elec_election', sa.Column('name', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_column('elec_election', 'type')
    op.add_column('elec_candidate', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('elec_candidate', sa.Column('election_event_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('elec_candidate_election_event_id_fkey', 'elec_candidate', 'elec_event', ['election_event_id'], ['id'])
    op.alter_column('elec_candidate', 'person_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('elec_candidate', 'raw_name')
    op.alter_column('ai_embedding_model', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('ai_embedding_model', 'version')
    op.drop_column('ai_embedding', 'vector')
    op.drop_constraint(None, 'ai_chunk', type_='foreignkey')
    op.alter_column('ai_chunk', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('ai_chunk', 'content_version_id')
    op.create_table('addr',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tlid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('fromhn', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('tohn', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('side', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('zip', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('plus4', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('fromtyp', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('totyp', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('fromarmid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('toarmid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('arid', sa.VARCHAR(length=22), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name='addr_pkey')
    )
    op.create_index('idx_tiger_addr_zip', 'addr', ['zip'], unique=False)
    op.create_index('idx_tiger_addr_tlid_statefp', 'addr', ['tlid', 'statefp'], unique=False)
    op.create_table('tract',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('tractce', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('tract_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('namelsad', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('awater', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_geom'),
    sa.PrimaryKeyConstraint('tract_id', name='tract_pkey')
    )
    op.create_table('geocode_settings',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('setting', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('short_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='geocode_settings_pkey')
    )
    op.create_table('faces',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tfid', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('statefp00', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp00', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('tractce00', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('blkgrpce00', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('blockce00', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('cousubfp00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('submcdfp00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('conctyfp00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('placefp00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('aiannhfp00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('aiannhce00', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('comptyp00', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('trsubfp00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('trsubce00', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('anrcfp00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('elsdlea00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('scsdlea00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('unsdlea00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('uace00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('cd108fp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('sldust00', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('sldlst00', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('vtdst00', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('zcta5ce00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('tazce00', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('ugace00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('puma5ce00', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('tractce', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('blkgrpce', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('blockce', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('cousubfp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('submcdfp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('conctyfp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('placefp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('aiannhfp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('aiannhce', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('comptyp', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('trsubfp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('trsubce', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('anrcfp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('ttractce', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('tblkgpce', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('elsdlea', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('scsdlea', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('unsdlea', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('uace', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('cd111fp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('sldust', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('sldlst', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('vtdst', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('zcta5ce', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('tazce', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('ugace', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('puma5ce', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('csafp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('cbsafp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('metdivfp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('cnectafp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('nectafp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('nctadvfp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('lwflag', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('offset', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('atotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.Column('tractce20', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('blkgrpce20', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('blockce20', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('countyfp20', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('statefp20', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_the_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_the_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_the_geom'),
    sa.PrimaryKeyConstraint('gid', name='faces_pkey')
    )
    op.create_index('tiger_faces_the_geom_gist', 'faces', ['the_geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_tiger_faces_tfid', 'faces', ['tfid'], unique=False)
    op.create_index('idx_tiger_faces_countyfp', 'faces', ['countyfp'], unique=False)
    op.create_table('geocode_settings_default',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('setting', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('short_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='geocode_settings_default_pkey')
    )
    op.create_table('zip_state_loc',
    sa.Column('zip', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('stusps', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('place', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('zip', 'stusps', 'place', name='zip_state_loc_pkey')
    )
    op.create_table('tabblock',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('tractce', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('blockce', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('tabblock_id', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('ur', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('uace', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('awater', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_geom'),
    sa.PrimaryKeyConstraint('tabblock_id', name='tabblock_pkey')
    )
    op.create_table('zip_lookup',
    sa.Column('zip', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('st_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('co_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('county', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.Column('cs_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cousub', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.Column('pl_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('place', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.Column('cnt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('zip', name='zip_lookup_pkey')
    )
    op.create_table('state',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('division', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('statens', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('stusps', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsad', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('awater', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_the_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_the_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_the_geom'),
    sa.PrimaryKeyConstraint('statefp', name='pk_tiger_state'),
    sa.UniqueConstraint('gid', name='uidx_tiger_state_gid'),
    sa.UniqueConstraint('stusps', name='uidx_tiger_state_stusps')
    )
    op.create_index('idx_tiger_state_the_geom_gist', 'state', ['the_geom'], unique=False, postgresql_using='gist')
    op.create_table('layer',
    sa.Column('topology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_column', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topology_id'], ['topology.id'], name='layer_topology_id_fkey'),
    sa.PrimaryKeyConstraint('topology_id', 'layer_id', name='layer_pkey'),
    sa.UniqueConstraint('schema_name', 'table_name', 'feature_column', name='layer_schema_name_table_name_feature_column_key')
    )
    op.create_table('featnames',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tlid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('fullname', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('predirabrv', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('pretypabrv', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('prequalabr', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('sufdirabrv', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('suftypabrv', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sufqualabr', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('predir', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('pretyp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('prequal', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('sufdir', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('suftyp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('sufqual', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('linearid', sa.VARCHAR(length=22), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('paflag', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name='featnames_pkey')
    )
    op.create_index('idx_tiger_featnames_tlid_statefp', 'featnames', ['tlid', 'statefp'], unique=False)
    op.create_index('idx_tiger_featnames_snd_name', 'featnames', [sa.text('soundex(name::text)')], unique=False)
    op.create_index('idx_tiger_featnames_lname', 'featnames', [sa.text('lower(name::text)')], unique=False)
    op.create_table('bg',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('tractce', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('blkgrpce', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('bg_id', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('namelsad', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('awater', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_geom'),
    sa.PrimaryKeyConstraint('bg_id', name='bg_pkey'),
    comment='block groups'
    )
    op.create_table('county_lookup',
    sa.Column('st_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('co_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('st_code', 'co_code', name='county_lookup_pkey')
    )
    op.create_index('county_lookup_state_idx', 'county_lookup', ['state'], unique=False)
    op.create_index('county_lookup_name_idx', 'county_lookup', [sa.text('soundex(name::text)')], unique=False)
    op.create_table('loader_variables',
    sa.Column('tiger_year', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('website_root', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('staging_fold', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_schema', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('staging_schema', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tiger_year', name='loader_variables_pkey')
    )
    op.create_table('addrfeat',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tlid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('aridl', sa.VARCHAR(length=22), autoincrement=False, nullable=True),
    sa.Column('aridr', sa.VARCHAR(length=22), autoincrement=False, nullable=True),
    sa.Column('linearid', sa.VARCHAR(length=22), autoincrement=False, nullable=True),
    sa.Column('fullname', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lfromhn', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('ltohn', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('rfromhn', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('rtohn', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('zipl', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('zipr', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('edge_mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('parityl', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('parityr', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('plus4l', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('plus4r', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('lfromtyp', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('ltotyp', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('rfromtyp', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('rtotyp', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('offsetl', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('offsetr', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'LINESTRING'::text OR the_geom IS NULL", name='enforce_geotype_the_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_the_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_the_geom'),
    sa.PrimaryKeyConstraint('gid', name='addrfeat_pkey')
    )
    op.create_index('idx_addrfeat_zipr', 'addrfeat', ['zipr'], unique=False)
    op.create_index('idx_addrfeat_zipl', 'addrfeat', ['zipl'], unique=False)
    op.create_index('idx_addrfeat_tlid', 'addrfeat', ['tlid'], unique=False)
    op.create_index('idx_addrfeat_geom_gist', 'addrfeat', ['the_geom'], unique=False, postgresql_using='gist')
    op.create_table('direction_lookup',
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('abbrev', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='direction_lookup_pkey')
    )
    op.create_index('direction_lookup_abbrev_idx', 'direction_lookup', ['abbrev'], unique=False)
    op.create_table('street_type_lookup',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('abbrev', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_hw', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='street_type_lookup_pkey')
    )
    op.create_index('street_type_lookup_abbrev_idx', 'street_type_lookup', ['abbrev'], unique=False)
    op.create_table('countysub_lookup',
    sa.Column('st_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('co_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('county', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.Column('cs_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('st_code', 'co_code', 'cs_code', name='countysub_lookup_pkey')
    )
    op.create_index('countysub_lookup_state_idx', 'countysub_lookup', ['state'], unique=False)
    op.create_index('countysub_lookup_name_idx', 'countysub_lookup', [sa.text('soundex(name::text)')], unique=False)
    op.create_table('place',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('placefp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('placens', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('plcidfp', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('namelsad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsad', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('classfp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('cpi', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('pcicbsa', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('pcinecta', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('awater', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_the_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_the_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_the_geom'),
    sa.PrimaryKeyConstraint('plcidfp', name='place_pkey'),
    sa.UniqueConstraint('gid', name='uidx_tiger_place_gid')
    )
    op.create_index('tiger_place_the_geom_gist', 'place', ['the_geom'], unique=False, postgresql_using='gist')
    op.create_table('zcta5',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('zcta5ce', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('classfp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('awater', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('partflg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_the_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_the_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_the_geom'),
    sa.PrimaryKeyConstraint('zcta5ce', 'statefp', name='pk_tiger_zcta5_zcta5ce'),
    sa.UniqueConstraint('gid', name='uidx_tiger_zcta5_gid')
    )
    op.create_table('loader_platform',
    sa.Column('os', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('declare_sect', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pgbin', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wget', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unzip_command', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('psql', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('path_sep', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('loader', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('environ_set_command', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('county_process_command', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('os', name='loader_platform_pkey')
    )
    op.create_table('edges',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('tlid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('tfidl', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('tfidr', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('fullname', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('smid', sa.VARCHAR(length=22), autoincrement=False, nullable=True),
    sa.Column('lfromadd', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('ltoadd', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('rfromadd', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('rtoadd', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('zipl', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('zipr', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('featcat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('hydroflg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('railflg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('roadflg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('olfflg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('passflg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('divroad', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('exttyp', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('ttyp', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('deckedroad', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('artpath', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('persist', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('gcseflg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('offsetl', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('offsetr', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('tnidf', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('tnidt', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTILINESTRING'::text OR the_geom IS NULL", name='enforce_geotype_the_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_the_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_the_geom'),
    sa.PrimaryKeyConstraint('gid', name='edges_pkey')
    )
    op.create_index('idx_tiger_edges_the_geom_gist', 'edges', ['the_geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_tiger_edges_countyfp', 'edges', ['countyfp'], unique=False)
    op.create_index('idx_edges_tlid', 'edges', ['tlid'], unique=False)
    op.create_table('zip_lookup_all',
    sa.Column('zip', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('st_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('co_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('county', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.Column('cs_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cousub', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.Column('pl_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('place', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.Column('cnt', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('tabblock20',
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('tractce', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('blockce', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('geoid', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('ur', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('uace', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('uatype', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('awater', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4269, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.Column('housing', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pop', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('geoid', name='pk_tabblock20')
    )
    op.create_table('state_lookup',
    sa.Column('st_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('abbrev', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('statefp', sa.CHAR(length=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('st_code', name='state_lookup_pkey'),
    sa.UniqueConstraint('abbrev', name='state_lookup_abbrev_key'),
    sa.UniqueConstraint('name', name='state_lookup_name_key'),
    sa.UniqueConstraint('statefp', name='state_lookup_statefp_key')
    )
    op.create_table('cousub',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('cousubfp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('cousubns', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('cosbidfp', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('namelsad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsad', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('classfp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('cnectafp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('nectafp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('nctadvfp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.NUMERIC(precision=14, scale=0), autoincrement=False, nullable=True),
    sa.Column('awater', sa.NUMERIC(precision=14, scale=0), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_the_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_the_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_the_geom'),
    sa.PrimaryKeyConstraint('cosbidfp', name='cousub_pkey'),
    sa.UniqueConstraint('gid', name='uidx_cousub_gid')
    )
    op.create_index('tige_cousub_the_geom_gist', 'cousub', ['the_geom'], unique=False, postgresql_using='gist')
    op.create_table('loader_lookuptables',
    sa.Column('process_order', sa.INTEGER(), server_default=sa.text('1000'), autoincrement=False, nullable=False),
    sa.Column('lookup_name', sa.TEXT(), autoincrement=False, nullable=False, comment='This is the table name to inherit from and suffix of resulting output table -- how the table will be named --  edges here would mean -- ma_edges , pa_edges etc. except in the case of national tables. national level tables have no prefix'),
    sa.Column('table_name', sa.TEXT(), autoincrement=False, nullable=True, comment='suffix of the tables to load e.g.  edges would load all tables like *edges.dbf(shp)  -- so tl_2010_42129_edges.dbf .  '),
    sa.Column('single_mode', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('load', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment="Whether or not to load the table.  For states and zcta5 (you may just want to download states10, zcta510 nationwide file manually) load your own into a single table that inherits from tiger.states, tiger.zcta5.  You'll get improved performance for some geocoding cases."),
    sa.Column('level_county', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('level_state', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('level_nation', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='These are tables that contain all data for the whole US so there is just a single file'),
    sa.Column('post_load_process', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('single_geom_mode', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('insert_mode', sa.CHAR(length=1), server_default=sa.text("'c'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('pre_load_process', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('columns_exclude', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True, comment='List of columns to exclude as an array. This is excluded from both input table and output table and rest of columns remaining are assumed to be in same order in both tables. gid, geoid,cpi,suffix1ce are excluded if no columns are specified.'),
    sa.Column('website_root_override', sa.TEXT(), autoincrement=False, nullable=True, comment='Path to use for wget instead of that specified in year table.  Needed currently for zcta where they release that only for 2000 and 2010'),
    sa.PrimaryKeyConstraint('lookup_name', name='loader_lookuptables_pkey')
    )
    op.create_table('pagc_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pagc_rules_pkey')
    )
    op.create_table('place_lookup',
    sa.Column('st_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('pl_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('st_code', 'pl_code', name='place_lookup_pkey')
    )
    op.create_index('place_lookup_state_idx', 'place_lookup', ['state'], unique=False)
    op.create_index('place_lookup_name_idx', 'place_lookup', [sa.text('soundex(name::text)')], unique=False)
    op.create_table('topology',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hasz', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='topology_pkey'),
    sa.UniqueConstraint('name', name='topology_name_key')
    )
    op.create_table('county',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('countyns', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('cntyidfp', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('namelsad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsad', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('classfp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('csafp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('cbsafp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('metdivfp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('awater', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_geom'),
    sa.PrimaryKeyConstraint('cntyidfp', name='pk_tiger_county'),
    sa.UniqueConstraint('gid', name='uidx_county_gid')
    )
    op.create_index('idx_tiger_county', 'county', ['countyfp'], unique=False)
    op.create_table('pagc_gaz',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('word', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stdword', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pagc_gaz_pkey')
    )
    op.create_table('zip_lookup_base',
    sa.Column('zip', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('county', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('zip', name='zip_lookup_base_pkey')
    )
    op.create_table('pagc_lex',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('word', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stdword', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pagc_lex_pkey')
    )
    op.create_table('zip_state',
    sa.Column('zip', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('stusps', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('zip', 'stusps', name='zip_state_pkey')
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('secondary_unit_lookup',
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('abbrev', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='secondary_unit_lookup_pkey')
    )
    op.create_index('secondary_unit_lookup_abbrev_idx', 'secondary_unit_lookup', ['abbrev'], unique=False)
    op.drop_table('src_embedding_version')
    op.drop_table('src_ocr_version')
    op.drop_table('src_extracted_text_version')
    op.drop_table('src_chunk_version')
    op.drop_table('prov_canonical_fact')
    # ### end Alembic commands ###
