"""p3_registry_endpoint_expansion

Revision ID: f1c2c1d84e03
Revises: c184b591c559
Create Date: 2026-08-22 13:47:49.305869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c2c1d84e03'
down_revision = 'c184b591c559'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('src_endpoint', sa.Column('canonical_url', sa.String(length=2048), nullable=True))
    op.add_column('src_endpoint', sa.Column('endpoint_type', sa.String(length=100), nullable=True))
    op.add_column('src_endpoint', sa.Column('expected_format', sa.String(length=100), nullable=True))
    op.add_column('src_endpoint', sa.Column('discovery_method', sa.String(length=100), nullable=True))
    op.add_column('src_endpoint', sa.Column('refresh_frequency', sa.String(length=100), nullable=True))
    op.add_column('src_endpoint', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('src_endpoint', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('src_endpoint', sa.Column('error_count', sa.Integer(), nullable=True))
    op.add_column('src_endpoint', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('src_endpoint', sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True))
    op.add_column('src_endpoint', sa.Column('last_success', sa.DateTime(timezone=True), nullable=True))
    op.add_column('src_endpoint', sa.Column('last_failure', sa.DateTime(timezone=True), nullable=True))
    op.add_column('src_endpoint', sa.Column('checksum', sa.String(length=256), nullable=True))
    op.add_column('src_source', sa.Column('public_id', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('official_name', sa.String(length=512), nullable=True))
    op.add_column('src_source', sa.Column('authority_level', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('government_level', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('department', sa.String(length=256), nullable=True))
    op.add_column('src_source', sa.Column('subcategory', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('canonical_url', sa.String(length=2048), nullable=True))
    op.add_column('src_source', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('src_source', sa.Column('source_type', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('access_method', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('attribution', sa.Text(), nullable=True))
    op.add_column('src_source', sa.Column('terms_url', sa.String(length=2048), nullable=True))
    op.add_column('src_source', sa.Column('robots_policy', sa.String(length=200), nullable=True))
    op.add_column('src_source', sa.Column('contact_url', sa.String(length=2048), nullable=True))
    op.add_column('src_source', sa.Column('api_available', sa.Boolean(), nullable=True))
    op.add_column('src_source', sa.Column('authentication_required', sa.Boolean(), nullable=True))
    op.add_column('src_source', sa.Column('rate_limit', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('refresh_policy', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('src_source', sa.Column('trust_level', sa.String(length=100), nullable=True))
    op.add_column('src_source', sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('src_source', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('src_source', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('src_source', sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('src_source', sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('src_source', sa.Column('next_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'src_source', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'src_source', type_='unique')
    op.drop_column('src_source', 'next_scheduled_at')
    op.drop_column('src_source', 'last_failure_at')
    op.drop_column('src_source', 'last_success_at')
    op.drop_column('src_source', 'last_checked_at')
    op.drop_column('src_source', 'verified_at')
    op.drop_column('src_source', 'discovered_at')
    op.drop_column('src_source', 'trust_level')
    op.drop_column('src_source', 'priority')
    op.drop_column('src_source', 'refresh_policy')
    op.drop_column('src_source', 'rate_limit')
    op.drop_column('src_source', 'authentication_required')
    op.drop_column('src_source', 'api_available')
    op.drop_column('src_source', 'contact_url')
    op.drop_column('src_source', 'robots_policy')
    op.drop_column('src_source', 'terms_url')
    op.drop_column('src_source', 'attribution')
    op.drop_column('src_source', 'access_method')
    op.drop_column('src_source', 'source_type')
    op.drop_column('src_source', 'description')
    op.drop_column('src_source', 'canonical_url')
    op.drop_column('src_source', 'subcategory')
    op.drop_column('src_source', 'department')
    op.drop_column('src_source', 'district')
    op.drop_column('src_source', 'state')
    op.drop_column('src_source', 'country')
    op.drop_column('src_source', 'government_level')
    op.drop_column('src_source', 'authority_level')
    op.drop_column('src_source', 'official_name')
    op.drop_column('src_source', 'public_id')
    op.drop_column('src_endpoint', 'checksum')
    op.drop_column('src_endpoint', 'last_failure')
    op.drop_column('src_endpoint', 'last_success')
    op.drop_column('src_endpoint', 'last_checked')
    op.drop_column('src_endpoint', 'retry_count')
    op.drop_column('src_endpoint', 'error_count')
    op.drop_column('src_endpoint', 'enabled')
    op.drop_column('src_endpoint', 'priority')
    op.drop_column('src_endpoint', 'refresh_frequency')
    op.drop_column('src_endpoint', 'discovery_method')
    op.drop_column('src_endpoint', 'expected_format')
    op.drop_column('src_endpoint', 'endpoint_type')
    op.drop_column('src_endpoint', 'canonical_url')
    # ### end Alembic commands ###
